### ISSUE TITLE
Can't get the key value when using setChoicesFromKeys

### ISSUE THREAD

**Issue by menico** [chrismiles/EZForm#59]
I can't get the key value when using setChoicesFromKeys i only get the value.

Is there a way of getting the key value instead of the value itself?

My output is:

< EZFormInputControl: 0x17600220; baseClass = UIControl; frame = (12 516; 277 30); text = 'Space'; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x175d4a60>; layer = <CALayer: 0x17600120>>

There is no Key variable

Thanks

Meni

**Comment by amcastror** [comment]
Hi, were you able to pull this off?
